name: hongwei87
favicon: null
layout_spectrum: 0.7677005485165864
typography_spectrum: 0.39474818925373256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.38712341780774295
  lightness: 0.8712073147762567
  saturation: 0.5557873081415892
  rhythmicContrast: 0.12292232410982251
purpose: []
